/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deneme;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author asuss
 */
public class Blok_bilgi extends javax.swing.JFrame {

    
    private Connection baglanti;
    private ResultSet sonuc;
    private Statement ifade;
    
   
    
    private DAO dao = new DAO();

    private void VerileriGetir()
    {
        String sql = "SELECT * FROM \"BLOK\"";
        try
        {
            
                baglanti = dao.getBaglanti();
                ifade = baglanti.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
                sonuc = ifade.executeQuery(sql);
                sonuc.next();
               //ifade.close();
                
              
            
            
           
        }
        catch(SQLException ex)
        {
            ex.printStackTrace();
        }
    }
    
    private void txtBosalt()
    {
        txt_blok_adi.setText("");
        txt_blok_no.setText("");
        txt_kat_sayisi.setText("");
        txt_daire_sayisi.setText("");
        txt_blok_no.requestFocus();
        
    }
    
    private void VerileriGoster()
    {
        txtBosalt();
        
      
        if(sonuc != null)
        {
            try {
                txt_blok_adi.setText(sonuc.getString("blok_adi"));
                txt_blok_no.setText(sonuc.getString("blok_no"));
                txt_kat_sayisi.setText(sonuc.getString("kat_sayisi"));
                txt_daire_sayisi.setText(sonuc.getString("daire_sayisi"));
                String var="var";
                if (sonuc.getString("asansor_durumu").equals(var))
                {
                cmb_asansor.setSelectedIndex(0);
                }   
                else {
                cmb_asansor.setSelectedIndex(1);
                }
                
                } catch (SQLException ex) 
                {
                ex.printStackTrace();
                }
        }
        
    }
    public void ayarla(){
       try {
                
                sonuc=ifade.executeQuery("SELECT site_adi FROM \"SITE\"");
                sonuc.next(); 
                sonuc.first();
                txt_siteadi.setText(sonuc.getString("site_adi"));
                ifade.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
   }
    
    public void baslangic()
    {
       // txtBosalt();
        VerileriGetir();
        //VerileriGoster();
        //ayarla();
    }
    public Blok_bilgi() {
        initComponents();
        baslangic();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_arama = new javax.swing.JTextField();
        txt_blok_no = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_blok_adi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_daire_sayisi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_kat_sayisi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_sil = new javax.swing.JButton();
        btn_arama = new javax.swing.JButton();
        btn_guncelle = new javax.swing.JButton();
        txt_kayit = new javax.swing.JButton();
        txt_islem = new javax.swing.JTextField();
        txt_siteadi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmb_asansor = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Blok Numarası");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Blok Adı");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Daire Sayısı");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Kat sayısı");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Asansör Durumu");

        btn_sil.setText("Sil");
        btn_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_silActionPerformed(evt);
            }
        });

        btn_arama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_arama.setText("blok numarasına göre ara");
        btn_arama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aramaActionPerformed(evt);
            }
        });

        btn_guncelle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_guncelle.setText("guncelle");
        btn_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guncelleActionPerformed(evt);
            }
        });

        txt_kayit.setText("kaydet");
        txt_kayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kayitActionPerformed(evt);
            }
        });

        txt_islem.setEditable(false);
        txt_islem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_islemActionPerformed(evt);
            }
        });

        txt_siteadi.setEditable(false);

        jLabel6.setText("SİTE ADI");

        cmb_asansor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmb_asansor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Evet", "Hayır" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_kayit)
                                .addGap(18, 18, 18)
                                .addComponent(btn_guncelle)
                                .addGap(18, 18, 18)
                                .addComponent(btn_sil))
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_islem, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_daire_sayisi, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(txt_kat_sayisi)
                            .addComponent(txt_blok_adi)
                            .addComponent(txt_blok_no, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(cmb_asansor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_arama, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_arama)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_siteadi, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_blok_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_blok_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_daire_sayisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_kat_sayisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_kayit)
                            .addComponent(btn_guncelle)
                            .addComponent(btn_sil))
                        .addGap(18, 18, 18)
                        .addComponent(txt_islem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmb_asansor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_arama)
                            .addComponent(txt_arama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_siteadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Site_bilgi site = new Site_bilgi();
    private void txt_kayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kayitActionPerformed
           
            ayarla();
          
            String blok_no = txt_blok_no.getText();
            String blok_adi = txt_blok_adi.getText();
            String daire_sayisi = txt_daire_sayisi.getText();
            String kat_sayisi = txt_kat_sayisi.getText();
            String asansor;
            if (cmb_asansor.getSelectedIndex() == 0)
            {
            asansor = "var";
            }   
            else {
            asansor = "yok";
            }
            int blok_no_int = Integer.parseInt(txt_blok_no.getText());
            int daire_sayisi_int = Integer.parseInt(txt_daire_sayisi.getText());
            int kat_sayisi_int = Integer.parseInt(txt_kat_sayisi.getText());
            String site_adi = txt_siteadi.getText();
            
            
            String sql = "INSERT INTO \"BLOK\" (blok_adi,asansor_durumu,blok_no,kat_sayisi,daire_sayisi,site_adi) VALUES('"+blok_adi+"', '"+asansor+"', "+blok_no_int+", "+kat_sayisi_int+", "+daire_sayisi_int+", '"+site_adi+"' )";
            try{
                
                
                ifade = baglanti.createStatement();
                //System.out.println(sql);
                ifade.execute(sql);
                //ifade.close();
                VerileriGetir();
                //VerileriGoster();
                txtBosalt();
                //VerileriGoster();
            } catch (SQLException e) {
                e.printStackTrace();
            }
            
            String islem = "KAYDETME İSLEMİNİZ\nTAMAMLANMISTIR";
            txt_islem.setText(islem);
        
    }//GEN-LAST:event_txt_kayitActionPerformed

    private void btn_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_silActionPerformed
        try
        {
            ifade = baglanti.createStatement();
            String sql = " DELETE FROM \"BLOK\" "+" WHERE blok_no = '"+txt_blok_no.getText()+"' ";
            System.out.println(sql);
            ifade.execute(sql);
            
            //VerileriGetir();
            //VerileriGoster();
        
            //sonuc.deleteRow();
            //sonuc.close();
            ifade.close();
            VerileriGetir();
            txtBosalt();
            String islem = "SİLME İSLEMİNİZ\nTAMAMLANMISTIR";
            txt_islem.setText(islem);
            //VerileriGoster();
        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btn_silActionPerformed

    private void txt_islemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_islemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_islemActionPerformed

    private void btn_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guncelleActionPerformed
        String blok_no = txt_blok_no.getText();
        String blok_adi = txt_blok_adi.getText();
        String daire_sayisi = txt_daire_sayisi.getText();
        String kat_sayisi = txt_kat_sayisi.getText();
        String asansor;
            if (cmb_asansor.getSelectedIndex() == 0)
            {
            asansor = "var";
            }   
            else {
            asansor = "yok";
            }
        int blok_no_int = Integer.parseInt(txt_blok_no.getText());
        int daire_sayisi_int = Integer.parseInt(txt_daire_sayisi.getText());
        int kat_sayisi_int = Integer.parseInt(txt_kat_sayisi.getText());
        
         try
        {
            ifade = baglanti.createStatement();
            String sql = " UPDATE \"BLOK\" SET "+
                    "blok_no="+blok_no_int+
                    ", blok_adi='"+blok_adi+"'"+
                    ", daire_sayisi="+daire_sayisi_int+
                    ", kat_sayisi="+kat_sayisi_int+
                    ", asansor_durumu='"+asansor+"'"+
                    " WHERE blok_no = '"+txt_blok_no.getText()+"' ";
            System.out.println(sql);
            ifade.execute(sql);
            ifade.close();
            VerileriGetir();
            VerileriGoster();
            txtBosalt();
            String islem = "GUNCELLEME İSLEMİNİZ\nTAMAMLANMISTIR";
            txt_islem.setText(islem);
            //txtBosalt();
            //VerileriGoster();
        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_btn_guncelleActionPerformed

    private void btn_aramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aramaActionPerformed
        
        String blok_numarasi = txt_arama.getText();
        int blok_no_int = Integer.parseInt(blok_numarasi);
       VerileriGetir();
        
        try {
            
            int mevcut_satir;
            mevcut_satir = sonuc.getRow(); 
            sonuc.first();
            sonuc.previous();
            int satir = 0;
            boolean bulundu = false;
           
            while(sonuc.next())
            {
                satir++;
                
                if(sonuc.getInt("blok_no") == blok_no_int)
                {
                    bulundu = true;
                    break;
                }
            }
            if(bulundu)
            {
                sonuc.absolute(satir);
            }   
            else
            {
                 sonuc.absolute(mevcut_satir);
            }
            
            
            VerileriGoster();
           
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_aramaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Blok_bilgi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Blok_bilgi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Blok_bilgi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Blok_bilgi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Blok_bilgi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_arama;
    private javax.swing.JButton btn_guncelle;
    private javax.swing.JButton btn_sil;
    private javax.swing.JComboBox cmb_asansor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txt_arama;
    private javax.swing.JTextField txt_blok_adi;
    private javax.swing.JTextField txt_blok_no;
    private javax.swing.JTextField txt_daire_sayisi;
    private javax.swing.JTextField txt_islem;
    private javax.swing.JTextField txt_kat_sayisi;
    private javax.swing.JButton txt_kayit;
    private javax.swing.JTextField txt_siteadi;
    // End of variables declaration//GEN-END:variables
}
